[package]
name = "libconsolegameengine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libarl = { git = "https://github.com/coderarjob/libarl", branch = "master" }
